---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-deployment
  labels:
    app: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
        - name: go-demo
          image: <DOCKER_REGISTRY>/go-pks-demo:<VERSION>
          imagePullPolicy: Always
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "4000"
spec:
  type: LoadBalancer
  selector:
    app: go-demo
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
