version: "3"
services:
  app:
    container_name: app
    image: vs-go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - back-tier
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - back-tier
networks:
  back-tier:
