{
 "title": "VS App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vs_app_http_request_ops_total[2m]))",
     "legendFormat": "http"
    }
   ]
  },
  {
   "title": "Response Time -  0.99 Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(vs_app_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\", pod=~\"go-demo.*\"})",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\"})",
     "legendFormat": "Running "
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Memory Usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\", container=\"go-demo\"}",
     "legendFormat": "{{spec_ip}} : {{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage (per pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"default\", container=\"go-demo\"}[3m])) by (pod)",
     "legendFormat": "{{spec_ip}} : {{pod}}"
    }
   ]
  }
 ]
}