name: github-actions-demo
on: [push]
jobs:
  golang-unit-tests:
    runs-on: [self-hosted, linux, demo]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: egor-tensin/setup-gcc@v1
      - run: go version
      - run: ./task_run_tests.sh
  codacy-sast:
    runs-on: [self-hosted, linux, demo]
    steps:
      - run: echo "Run Codacy SAST"
  deploy-sit:
    runs-on: [self-hosted, linux, demo, docker]
    needs: [golang-unit-tests, codacy-sast]
    steps:
      - run: echo "Deploy to SIT"
  cypress-integration-test:
    runs-on: [self-hosted, linux, demo, docker]
    needs: deploy-sit
    steps:
      - run: echo "Run Cypress Integration Tests"
  production-approval:
    runs-on: [self-hosted, linux, demo]
    needs: cypress-integration-test
    steps:
      - run: echo "Production Deployment Approval"
  deploy-prod:
    runs-on: [self-hosted, linux, demo, kind]
    needs: production-approval
    steps:
      - run: echo "Deploy to Production"

